service: MLB

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  memorySize: 256
  #deploymentBucket: guru.dgl.${self:provider.region}.deploys
  #role: arn:aws::MLB:role/role
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:*:*:*"

functions:
  createBowler:
    handler: bowlers/create.create
    events:
      - http:
          path: bowler
          method: post
          cors: true

  listBowlers:
    handler: bowlers/list.list
    events:
      - http:
          path: bowlers
          method: get
          cors: true

  getBowler:
    handler: bowlers/get.get
    events:
      - http:
          path: bowler/{name}
          method: get
          cors: true

  updateBowler:
    handler: bowlers/update.update
    events:
      - http:
          path: bowler/{name}
          method: put
          cors: true

  deleteBowler:
    handler: bowlers/delete.delete
    events:
      - http:
          path: bowler/{name}
          method: delete
          cors: true
          
  createEvent:
    handler: events/create.create
    events:
      - http:
          path: event
          method: post
          cors: true


  listEvents:
    handler: events/list.list
    events:
      - http:
          path: events/{season}
          method: get
          cors: true

  getEvent:
    handler: events/get.get
    events:
      - http:
          path: event/{date}
          method: get
          cors: true

  updateEvent:
    handler: events/update.update
    events:
      - http:
          path: event/{date}
          method: put
          cors: true

  deleteEvent:
    handler: events/delete.delete
    events:
      - http:
          path: event/{date}
          method: delete
          cors: true

resources:
  Resources:
    BowlerTable:
      Type: 'AWS::DynamoDB::Table'
      #DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: "name"
            AttributeType: S
        KeySchema:
          - AttributeName: "name"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'mlb_bowler'
    EventTable:
      Type: 'AWS::DynamoDB::Table'
      #DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: "date"
            AttributeType: S
          - AttributeName: "season"
            AttributeType: S
        KeySchema:
          - AttributeName: "date"
            KeyType: "HASH"
          - AttributeName: "season"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'mlb_event'
